# fly.toml app configuration file generated for wasdeenet on 2023-04-20T22:54:38+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wasdeenet"
primary_region = "sin"

kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
  PORT = "41641"
  # create a reusable auth key and set it:
  # flyctl secrets set TAILSCALE_AUTH_KEY=tskey-...
  # ephemeral keys are hardly working for use as exit node as they are ipv6 only

[[services]]
  protocol = "udp"
  internal_port = 41641
  processes = ["app"]

  [[services.ports]]
    port = 41641
  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 75
